project_id = "bfulrloxjoyaiuygmdgx"

[functions.generate-payment-hash]
verify_jwt = true

[functions.generate-payu-hash]
verify_jwt = false

[functions.realtime-voice]
verify_jwt = false

[functions.predict-price]
verify_jwt = false
