// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfulrloxjoyaiuygmdgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdWxybG94am95YWl1eWdtZGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTExNzcsImV4cCI6MjA3MzY2NzE3N30.9BhYaHla-2bKyYjunV5ma_k5sXjn4Y51ftzL7pXBn0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});